SECOND_IN_MILLISECONDS = 1000
MINUTE_IN_SECONDS = 60
HOUR_IN_SECONDS = MINUTE_IN_SECONDS * 60
DAY_IN_SECONDS = HOUR_IN_SECONDS * 24

DEFAULT_NEWS_SWITCH_DELAY = 15
DEFAULT_NEWS_UPDATE_DELAY = 1 * HOUR_IN_SECONDS
DEFAULT_WEATHER_UPDATE_DELAY = 5 * MINUTE_IN_SECONDS

DB_FILENAME = "countdown.db"

DB_CREATE_TABLE_COMMAND = """
CREATE TABLE IF NOT EXISTS countdown(
	"name"	TEXT UNIQUE,
	"year"	INTEGER,
	"month"	INTEGER,
	"day"	INTEGER,
	PRIMARY KEY("name")
);
"""

DB_ADD_COUNTDOWN = """
INSERT INTO countdown VALUES ("%s", %d, %d, %d);
"""

DB_DELETE_COUNTDOWN = """
DELETE FROM countdown WHERE name = "%s";
"""
