SECOND_IN_MILLISECONDS = 1000
MINUTE_IN_SECONDS = 60
HOUR_IN_SECONDS = MINUTE_IN_SECONDS * 60
DAY_IN_SECONDS = HOUR_IN_SECONDS * 24

DEFAULT_NEWS_SWITCH_DELAY = 15
DEFAULT_NEWS_UPDATE_DELAY = 1 * HOUR_IN_SECONDS
DEFAULT_WEATHER_UPDATE_DELAY = 5 * MINUTE_IN_SECONDS
